apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 3
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: 844331382461.dkr.ecr.us-east-2.amazonaws.com/consumer:latest
        imagePullPolicy: Always
        env:
        - name: KAFKA_BROKER_URL
          value: "b-1.mskkafka.nybnzy.c4.kafka.us-east-2.amazonaws.com:9094,b-2.mskkafka.nybnzy.c4.kafka.us-east-2.amazonaws.com:9094"
        - name: KAFKA_TOPIC
          value: "posts"