name: Build and Push to ECR

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-2
  ECR_REGISTRY: 844331382461.dkr.ecr.us-east-2.amazonaws.com

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to ECR
      run: |
        aws ecr get-login-password --region $AWS_REGION \
        | docker login --username AWS --password-stdin $ECR_REGISTRY

    - name: Build Producer Image
      run: |
        docker build -t producer:latest ./app/producer
        docker tag producer:latest $ECR_REGISTRY/producer:latest

    - name: Build Consumer Image
      run: |
        docker build -t consumer:latest ./app/consumer
        docker tag consumer:latest $ECR_REGISTRY/consumer:latest

    - name: Push Images
      run: |
        docker push $ECR_REGISTRY/producer:latest
        docker push $ECR_REGISTRY/consumer:latest